# Generated by Django 3.0.8 on 2020-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
            ],
        ),
    ]
